from setuptools import setup

setup(
    name='id3-tagger',
    version='0.1',
    packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.pip',
              'venv.lib.python2.7.site-packages.pip.req', 'venv.lib.python2.7.site-packages.pip.vcs',
              'venv.lib.python2.7.site-packages.pip.utils', 'venv.lib.python2.7.site-packages.pip.compat',
              'venv.lib.python2.7.site-packages.pip.models', 'venv.lib.python2.7.site-packages.pip._vendor',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip.commands', 'venv.lib.python2.7.site-packages.pip.operations',
              'venv.lib.python2.7.site-packages.wheel', 'venv.lib.python2.7.site-packages.wheel.tool',
              'venv.lib.python2.7.site-packages.wheel.signatures', 'venv.lib.python2.7.site-packages.mutagen',
              'venv.lib.python2.7.site-packages.mutagen.asf', 'venv.lib.python2.7.site-packages.mutagen.id3',
              'venv.lib.python2.7.site-packages.mutagen.mp3', 'venv.lib.python2.7.site-packages.mutagen.mp4',
              'venv.lib.python2.7.site-packages.mutagen._senf', 'venv.lib.python2.7.site-packages.mutagen._tools',
              'venv.lib.python2.7.site-packages.setuptools', 'venv.lib.python2.7.site-packages.setuptools.extern',
              'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages.pkg_resources',
              'venv.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging', 'media', 'media.private', 'helpers'],
    url='https://github.com/brian978/id3-tagger',
    license='BSD 3-Clause License',
    author='brian978',
    author_email='',
    description='The repository hosts a small CLI application, based on the mutagen library, that allows you to set different ID3 tags on the supported audio files'
)
